development:
  adapter: postgresql
  encoding: utf8
  database: db/peterjskennedy_development
  pool: 5

test: &TEST
  min_messages: WARNING
  adapter: postgresql
  encoding: utf8
  database: db/peterjskennedy_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: db/peterjskennedy_production
  pool: 5